### ISSUE TITLE
Show stdout/stderr in the actual webhook

### ISSUE THREAD

**Issue by Poolitzer** [Nukesor/webhook-server#2]
This would make debugging way easier, and I dont think that anybody would get hurt by it. Right? 😮

**Comment by Nukesor** [comment]
What exactly do you mean by stdout/stderr?
If you refer to the stdout/stderr of the task executed by the server, this is impossible, since this is not how the server works.

The server has an internal scheduler, which propagates the tasks to a worker thread pool.
At the time of the initial webhook, it's unclear whether there are free slots in the worker pool and it's also unclear how long the tasks actually runs. If it runs longer than 5-10 seconds, many browsers/request implementations will throw a timeout exception anyway.

The current implementation allows the client to add tasks and get a confirmation that the task will be executed in the (probably) near future. Any further checks on whether the task is finished, scheduled or running can then be executed via the json index route.

**Comment by Poolitzer** [comment]
Hmm I see. Okay. I didnt look into the code yet, but I can totally understand why its not possible.
